# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KT Landscaping & Gardens
hide_background_title: true
email: ktlandscapingngardens@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

author: KT Sandura

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ktlandscaping.net" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
# github_username:
facebook_username: ktlandscapingardens
# linkedin_username:
# logo: assets/img/ic_launcher_round.png
logo: /assets/img/logo_no_slogan.png

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/posts/:num/"

collections:
  home_tiles:
    output: true

# = Defaults
defaults:
  - scope:
      path: ''
    values:
      background: "/assets/img/ktjumbotron3.jpg"
      background_title_logo: "/assets/img/logo_no_slogan.png"
      background_title_logo_height: "120px"
      jumbotrom_logo_height: "150px"
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      published: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
